/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-120228-g3334bdc6e7-20250711"
#endif /* AVUTIL_FFVERSION_H */
